services:
  - type: web
    name: ai-security-camera
    env: python
    plan: starter
    buildCommand: pip install Flask==2.3.0
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
